management:
    security:
        enabled: false
security:
    basic:
        enabled: false

spring:
    datasource:
        default-catalog: library
        jndi-name: jdbc/Library
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        show-sql: true


logging:
    file: /home/oleg/projects/ww/work/wwolwes/src/main/resources/app.log
    pattern:
      file: "%d{HH:mm:ss} %-5p [%c] - %m%n"

    level:
        ROOT: error
        org.springframework: info
        javax.faces: info
        org.omnifaces: info
        org.springframework.security: info
        org.hibernate: info
        org.hibernate.type.descriptor.sql: info